db.attendence.insert([
    {
        "user_id":"1",
        "topic_id":"1",
        "status":"present",
        "date":"2020-10-16"
    },
    {
        "user_id":"2",
        "topic_id":"2",
        "status":"present",
        "date":"2020-12-03"
    },
    {
        "user_id":"3",
        "topic_id":"1",
        "status":"absent",
        "date":"2020-10-18"
    },
    {
        "user_id":"4",
        "topic_id":"1",
        "status":"present",
        "date":"2020-11-18"
    },
    {
        "user_id":"2",
        "topic_id":"1",
        "status":"absent",
        "date":"2020-11-24"
    },
    {
        "user_id":"5",
        "topic_id":"2",
        "status":"present",
        "date":"2020-10-28"
    }
]);
