db.codekata.insert([
    {
        "user_id":"1",
        "level":"absolute beginner",
        "total_no_of_problems":30,
        "no_of_problems_solved":30
    },
    {
        "user_id":"1",
        "level":"Array",
        "total_no_of_problems":300,
        "no_of_problems_solved":150
    },
    {
        "user_id":"2",
        "level":"Array",
        "total_no_of_problems":300,
        "no_of_problems_solved":180
    },
    {
        "user_id":"3",
        "level":"String",
        "total_no_of_problems":200,
        "no_of_problems_solved":80
    },
    {
        "user_id":"4",
        "level":"String",
        "total_no_of_problems":200,
        "no_of_problems_solved":170
    },
    {
        "user_id":"5",
        "level":"Array",
        "total_no_of_problems":300,
        "no_of_problems_solved":270
    },
    {
        "user_id":"1",
        "level":"String",
        "total_no_of_problems":200,
        "no_of_problems_solved":170
    }]
    );
   
