db.company_drives.insert([{
"company_id":"1",
"company_name":"tcs",
"date":"2020-11-15",
"eligibility_criteria":"80%",
"no_of_students_appeared":"25",
"no_of_students_placed":"22",
},
{
"company_id":"2",
"company_name":"amazon",
"date":"2020-10-18",
"no_of_students_appeared":"32",
"no_of_students_placed":"28",
},
{
"company_id":"3",
"company_name":"freshworks",
"date":"2020-10-28",
"no_of_students_appeared":"25",
"no_of_students_placed":"23",
},
{"company_id":"4",
"company_name":"codingmart",
"date":"2020-11-29",
"no_of_students_appeared":"35",
"no_of_students_placed":"30",
},
{"company_id":"5",
"company_name":"flipkart",
"date":"2020-12-19",
"no_of_students_appeared":"22",
"no_of_students_placed":"21",
}])

db.company_drives.find();
   
