db.tasks.insert([{
"user_id":"1",
"task_id":"1",
"topic_id":"1",
"task_name":"functions and array in js",
"date":"2020-11-05",
"submitted_status":"yes"},
{
"user_id":"2",
"task_id":"1",
"topic_id":"1",
"task_name":"functions and array in js",
"date":"2020-11-15",
"submitted_status":"yes"},
{
"user_id":"2",
"task_id":"2",
"topic_id":"2",
"task_name":"html design page",
"date":"2020-10-18",
"submitted_status":"yes"},
{
"user_id":"3",
"task_id":"2",
"topic_id":"2",
"task_name":"html design page",
"date":"2020-10-25",
"submitted_status":"no"},
{
"user_id":"5",
"task_id":"3",
"topic_id":"3",
"task_name":"Design page using html and css",
"date":"2020-12-15",
"submitted_status":"yes"},
{
"user_id":"4",
"task_id":"2",
"topic_id":"2",
"task_name":"html design page",
"date":"2020-10-18",
"submitted_status":"no"},
{
"user_id":"2",
"task_id":"4",
"topic_id":"4",
"task_name":"crud application using formik reactjs",
"date":"2020-12-28",
"submitted_status":"yes"}])
