db.topics.insert([{
"topic_id":"1",
"topic_name":"Javascript",
"topics_taken":"Sivaranjini",
"month":"november"
},
{
"topic_id":"2",
"topic_name":"HTML",
"topics_taken":"Kumar",
"month":"october"
},
{
"topic_id":"3",
"topic_name":"CSS",
"topics_taken":"Deepika",
"month":"january"
},
{
"topic_id":"4",
"topic_name":"Reactjs",
"topics_taken":"Sivaranjini",
"month":"february"
},
{
"topic_id":"5",
"topic_name":"MySQL",
"topics_taken":"Gopinath",
"month":"march"
},
{
"topic_id":"6",
"topic_name":"MongoDB",
"topics_taken":"Sivaranjini",
"month":"april"
}])
